import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import ToastProvider from "../providers/ToastProvider";
import ReduxProvider from "../providers/ReduxProvider";
import ThemeProviderNext from "../providers/ThemeProvider";
import ModalProvider from "../providers/ModalProvider";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Messanger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviderNext>
        <ToastProvider />
        <ReduxProvider>
          <ModalProvider />
          {children}
          </ReduxProvider>
        </ThemeProviderNext>
      </body>
    </html>
  );
}
